#' School Dropouts by Race & Gender
#'
#' @description
#' Historical data for grade seven through twelve dropouts and enrollment by
#' race/ethnic designation and gender by school.
#'
#' @details
#' | **Field Name**  |   | **Description** |
#' |-------------|------|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
#' |  CDS_CODE   | `  ` | This 14-digit code is the official, unique identification of a  school within California. The first two digits identify the county, the  next five digits identify the school district, and the last seven digits  identify the school.  |
#' |    ETHNIC   | `  ` | This is a coded field for racial/ethnic designation. The racial/ethnic designations are coded as follows:                                                                                                                                |
#' |             | `  ` | ∙ Code 0 = Not reported                                                                                                                                                                                                                  |
#' |             | `  ` | ∙ Code 1 = American Indian or Alaska Native, Not Hispanic                                                                                                                                                                                |
#' |             | `  ` | ∙ Code 2 = Asian, Not Hispanic                                                                                                                                                                                                           |
#' |             | `  ` | ∙ Code 3 = Pacific Islander, Not Hispanic                                                                                                                                                                                                |
#' |             | `  ` | ∙ Code 4 = Filipino, Not Hispanic                                                                                                                                                                                                        |
#' |             | `  ` | ∙ Code 5 = Hispanic or Latino                                                                                                                                                                                                            |
#' |             | `  ` | ∙ Code 6 = African American, not Hispanic (formerly known as Black, not Hispanic)                                                                                                                                                        |
#' |             | `  ` | ∙ Code 7 = White, not Hispanic                                                                                                                                                                                                           |
#' |             | `  ` | ∙ Code 9 = Two or More Races, Not Hispanic.                                                                                                                                                                                              |
#' |    GENDER   | `  ` | This field is a coded field identifying gender. The gender is coded as follows:                                                                                                                                                          |
#' |             | `  ` | ∙ M = Male                                                                                                                                                                                                                               |
#' |             | `  ` | ∙ F = Female                                                                                                                                                                                                                             |
#' |     E7      | `  ` | Enrollment in grade seven. (Not included in enrollment total (ETOT) field below).                                                                                                                                                        |
#' |     E8      | `  ` | Enrollment in grade eight. (Not included in enrollment total (ETOT) field below).                                                                                                                                                        |
#' |     E9      | `  ` | Enrollment in grade nine.                                                                                                                                                                                                                |
#' |     E10     | `  ` | Enrollment in grade ten.                                                                                                                                                                                                                 |
#' |     E11     | `  ` | Enrollment in grade eleven.                                                                                                                                                                                                              |
#' |     E12     | `  ` | Enrollment in grade twelve.                                                                                                                                                                                                              |
#' |     EUS     | `  ` | Enrollment in ungraded secondary classes.                                                                                                                                                                                                |
#' |    ETOT     | `  ` | Total enrollment for grades nine through twelve and ungraded secondary. (Does not include grades seven and eight).                                                                                                                       |
#' |     D7      | `  ` | Dropouts in grade seven. (Not included in dropout total (DTOT) field below)                                                                                                                                                              |
#' |     D8      | `  ` | Dropouts in grade eight. (Not included in dropout total (DTOT) field below).                                                                                                                                                             |
#' |     D9      | `  ` | Dropouts in grade nine.                                                                                                                                                                                                                  |
#' |     D10     | `  ` | Dropouts in grade ten.                                                                                                                                                                                                                   |
#' |     D11     | `  ` | Dropouts in grade eleven.                                                                                                                                                                                                                |
#' |     D12     | `  ` | Dropouts in grade twelve.                                                                                                                                                                                                                |
#' |     DUS     | `  ` | Dropouts in ungraded secondary classes.                                                                                                                                                                                                  |
#' |    DTOT     | `  ` | Total dropouts for grades nine through twelve and ungraded secondary. (Does not include grades seven and eight).                                                                                                                         |
#' |    YEAR     | `  ` | Year of data.                                                                                                                                                                                                                            |
#'
#' Further questions regarding one-year dropout data can be sent by e-mail to
#' the Data Reporting Office at [dro@cde.ca.gov](dro@cde.ca.gov).
#'
#' @source
#' California Department of Education Data Reporting Office
#'
#' This data was downloaded 2023/01/20 at 13:00:29 EST and gathered from:
#' [https://www.cde.ca.gov/ds/ad/filesdropouts.asp](https://www.cde.ca.gov/ds/ad/filesdropouts.asp).
#'
#' @seealso \link{ca_schools},\link{ca_income_tax}
#'
"ca_dropouts"


#' California Public Schools and Districts
#'
#' @description
#' Contains all active, pending, closed, and merged public schools and
#' districts.
#'
#' @details
#' |  **Field Name**      |       | **Description**                                                                                                                                                                                                                                                                                                                                                                                                           |
#' |:---------------------|:-----:|:--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
#' | CDSCode              | `  `  | This 14-digit code is the official, unique identification of  a  school within California. The first two digits identify the county, the  next  five digits identify the school district, and the last seven  digits identify  the school. Please note that a CDS code ending in '0000000'  indicates a district record not a school.                                                                                     |
#' | NCESDist             | `  `  | This field represents the 7-digit National Center for Educational  Statistics (NCES)  school district identification number. The first 2  digits identify the state  and the last 5 digits identify the school  district. Combined, they make a  unique 7-digit ID for each school  district.                                                                                                                             |
#' | NCESSchool           | `  `  | This field represents the 5-digit NCES school identification number.  The NCESSchool combined with the NCESDist form a unique 12-digit ID for  each school.                                                                                                                                                                                                                                                               |
#' | StatusType           | `  `  | This field identifies the status of the district. Definitions of the valid status types are listed below:                                                                                                                                                                                                                                                                                                                 |
#' |                      | `  `  | ∙ _Active:_ The district is in operation and providing instructional services.                                                                                                                                                                                                                                                                                                                                            |
#' |                      | `  `  | ∙ _Closed:_ The district is not in operation and no longer providing instructional services.                                                                                                                                                                                                                                                                                                                              |
#' |                      | `  `  | ∙ _Merged:_ The district has combined with another district or districts.                                                                                                                                                                                                                                                                                                                                                 |
#' |                      | `  `  | ∙ _Pending:_ The district has not opened for operation and instructional services yet, but plans to open within the next 9–12 months.                                                                                                                                                                                                                                                                                     |
#' | County               | `  `  | County name.                                                                                                                                                                                                                                                                                                                                                                                                              |
#' | District             | `  `  | District or Administrative Authority name.                                                                                                                                                                                                                                                                                                                                                                                |
#' | School               | `  `  | School name.                                                                                                                                                                                                                                                                                                                                                                                                              |
#' | Street               | `  `  | The unabbreviated street (physical) address of this school, district, or administrative authority. Note: Some entities (primarily closed or retired schools) may not have data in this field.                                                                                                                                                                                                                             |
#' | StreetAbr            | `  `  | The abbreviated street address of the school, district, or  administrative  authority’s physical location. Note: Some records  (primarily records of closed  or retired schools) may not have data in  this field.                                                                                                                                                                                                        |
#' | City                 | `  `  | The city where the school, district, or administrative authority  is physically  located. Note: Some records (primarily records of closed  or retired schools)  may not have data in this field.                                                                                                                                                                                                                          |
#' | Zip                  | `  `  | The zip code associated with the street address of the school,  district, or  administrative authority’s physical location. Note: Some  records (primarily  records of closed or retired schools) may not have  data in this field.                                                                                                                                                                                       |
#' | State                | `  `  | The state in which the school, district, or administrative authority is located.                                                                                                                                                                                                                                                                                                                                          |
#' | MailStreet           | `  `  | The unabbreviated mailing address of the school, district, or  administrative  authority (i.e., P.O. Box). Note: 1) Some entities  (primarily closed or retired  schools) may not have data in this field;  2) Many active entities have not  provided a mailing street address. For  your convenience we have filled the  unpopulated MailStreet cells with  Street data.                                                |
#' | MailStrAbr           | `  `  | The abbreviated mailing street address of the school, district, or  administrative  authority (i.e., P.O. Box).Note: Many active entities  have not provided a  mailing street address. For your convenience we  have filled the unpopulated  MailStrAbr cells with StreetAbr data.                                                                                                                                       |
#' | MailCity             | `  `  | The city associated with the mailing address of the school,  district, or  administrative authority. Note: Many entities have not  provided a mailing  address city. For your convenience we have filled  the unpopulated MailCity  cells with City data.                                                                                                                                                                 |
#' | MailZip              | `  `  | The zip code associated with the mailing address of the school,  district, or  administrative authority. Note: Many entities have not  provided a mailing  address zip code. For your convenience we have  filled the unpopulated MailZip  cells with Zip data.                                                                                                                                                           |
#' | MailState            | `  `  | The state within the mailing address. For your convenience we have filled the  unpopulated MailState cells with State data.                                                                                                                                                                                                                                                                                               |
#' | Phone                | `  `  | The area code and phone number of the school, district, or administrative  authority.                                                                                                                                                                                                                                                                                                                                     |
#' | Ext                  | `  `  | The phone number extension of the school, district, or administrative authority.                                                                                                                                                                                                                                                                                                                                          |
#' | FaxNumber            | `  `  | The fax number of the school, district, or administrative authority.                                                                                                                                                                                                                                                                                                                                                      |
#' | Email                | `  `  | The email address of the school, district, or administrative authority.                                                                                                                                                                                                                                                                                                                                                   |
#' | Website              | `  `  | The website address of the school, district, or administrative authority.                                                                                                                                                                                                                                                                                                                                                 |
#' | OpenDate             | `  `  | The date the school opened.                                                                                                                                                                                                                                                                                                                                                                                               |
#' | ClosedDate           | `  `  | The date the school closed.                                                                                                                                                                                                                                                                                                                                                                                               |
#' | Charter              | `  `  | This field identifies a charter school. The field is coded as follows:                                                                                                                                                                                                                                                                                                                                                    |
#' |                      | `  `  | ∙ Y = The school is a charter                                                                                                                                                                                                                                                                                                                                                                                             |
#' |                      | `  `  | ∙ N = The school is not a charter                                                                                                                                                                                                                                                                                                                                                                                         |
#' | CharterNum           | `  `  | The charter school number, which is a 4-digit number assigned to a charter school.                                                                                                                                                                                                                                                                                                                                        |
#' | FundingType          | `  `  | Indicates the charter school funding type. Values are as follows:                                                                                                                                                                                                                                                                                                                                                         |
#' |                      | `  `  | ∙ Not in CS funding model                                                                                                                                                                                                                                                                                                                                                                                                 |
#' |                      | `  `  | ∙ Locally funded                                                                                                                                                                                                                                                                                                                                                                                                          |
#' |                      | `  `  | ∙ Directly funded                                                                                                                                                                                                                                                                                                                                                                                                         |
#' | DOC                  | `  `  | The District Ownership Code (DOC) is the numeric code used to identify the category of the Administrative Authority.                                                                                                                                                                                                                                                                                                      |
#' |                      | `  `  | ∙ 00 – County Office of Education                                                                                                                                                                                                                                                                                                                                                                                         |
#' |                      | `  `  | ∙ 02 – State Board of Education                                                                                                                                                                                                                                                                                                                                                                                           |
#' |                      | `  `  | ∙ 03 – Statewide Benefit Charter                                                                                                                                                                                                                                                                                                                                                                                          |
#' |                      | `  `  | ∙ 31 – State Special Schools                                                                                                                                                                                                                                                                                                                                                                                              |
#' |                      | `  `  | ∙ 34 – Non-school Location*                                                                                                                                                                                                                                                                                                                                                                                               |
#' |                      | `  `  | ∙ 52 – Elementary School District                                                                                                                                                                                                                                                                                                                                                                                         |
#' |                      | `  `  | ∙ 54 – Unified School District                                                                                                                                                                                                                                                                                                                                                                                            |
#' |                      | `  `  | ∙ 56 – High School District                                                                                                                                                                                                                                                                                                                                                                                               |
#' |                      | `  `  | ∙ 98 – Regional Occupational Center/Program (ROC/P)                                                                                                                                                                                                                                                                                                                                                                       |
#' |                      | `  `  | *Only the California Education Authority has been included in the non-school location category.                                                                                                                                                                                                                                                                                                                           |
#' | DOCType              | `  `  | The District Ownership Code Type is the text description of the DOC category. (See  text values in DOC field description above)                                                                                                                                                                                                                                                                                           |
#' | SOC                  | `  `  | The School Ownership Code is a numeric code used to identify the type of school.                                                                                                                                                                                                                                                                                                                                          |
#' |                      | `  `  | ∙ 08 – Preschool                                                                                                                                                                                                                                                                                                                                                                                                          |
#' |                      | `  `  | ∙ 09 – Special Education Schools (Public)                                                                                                                                                                                                                                                                                                                                                                                 |
#' |                      | `  `  | ∙ 10 – County Community                                                                                                                                                                                                                                                                                                                                                                                                   |
#' |                      | `  `  | ∙ 11 – Youth Authority Facilities (CEA)                                                                                                                                                                                                                                                                                                                                                                                   |
#' |                      | `  `  | ∙ 13 – Opportunity Schools                                                                                                                                                                                                                                                                                                                                                                                                |
#' |                      | `  `  | ∙ 14 – Juvenile Court Schools                                                                                                                                                                                                                                                                                                                                                                                             |
#' |                      | `  `  | ∙ 15 – Other County or District Programs                                                                                                                                                                                                                                                                                                                                                                                  |
#' |                      | `  `  | ∙ 31 – State Special Schools                                                                                                                                                                                                                                                                                                                                                                                              |
#' |                      | `  `  | ∙ 60 – Elementary School (Public)                                                                                                                                                                                                                                                                                                                                                                                         |
#' |                      | `  `  | ∙ 61 – Elementary School in 1 School District (Public)                                                                                                                                                                                                                                                                                                                                                                    |
#' |                      | `  `  | ∙ 62 – Intermediate/Middle Schools (Public)                                                                                                                                                                                                                                                                                                                                                                               |
#' |                      | `  `  | ∙ 63 – Alternative Schools of Choice                                                                                                                                                                                                                                                                                                                                                                                      |
#' |                      | `  `  | ∙ 64 – Junior High Schools (Public)                                                                                                                                                                                                                                                                                                                                                                                       |
#' |                      | `  `  | ∙ 65 – K-12 Schools (Public)                                                                                                                                                                                                                                                                                                                                                                                              |
#' |                      | `  `  | ∙ 66 – High Schools (Public)                                                                                                                                                                                                                                                                                                                                                                                              |
#' |                      | `  `  | ∙ 67 – High Schools in 1 School District (Public)                                                                                                                                                                                                                                                                                                                                                                         |
#' |                      | `  `  | ∙ 68 – Continuation High Schools                                                                                                                                                                                                                                                                                                                                                                                          |
#' |                      | `  `  | ∙ 69 – District Community Day Schools                                                                                                                                                                                                                                                                                                                                                                                     |
#' |                      | `  `  | ∙ 70 – Adult Education Centers                                                                                                                                                                                                                                                                                                                                                                                            |
#' |                      | `  `  | ∙ 98 – Regional Occupational Center/Program (ROC/P)                                                                                                                                                                                                                                                                                                                                                                       |
#' | SOCType              | `  `  | The School Ownership Code Type is the text description of  the type of school. (See text values in SOC field description above)                                                                                                                                                                                                                                                                                           |
#' | EdOpsCode            | `  `  | The Education Option Code is a short text description of the type of education offered.                                                                                                                                                                                                                                                                                                                                   |
#' |                      | `  `  | ∙ ALTSOC – Alternative School of Choice                                                                                                                                                                                                                                                                                                                                                                                   |
#' |                      | `  `  | ∙ COMM – County Community School                                                                                                                                                                                                                                                                                                                                                                                          |
#' |                      | `  `  | ∙ COMMDAY – Community Day School                                                                                                                                                                                                                                                                                                                                                                                          |
#' |                      | `  `  | ∙ CON – Continuation School                                                                                                                                                                                                                                                                                                                                                                                               |
#' |                      | `  `  | ∙ JUV – Juvenile Court School                                                                                                                                                                                                                                                                                                                                                                                             |
#' |                      | `  `  | ∙ OPP – Opportunity School                                                                                                                                                                                                                                                                                                                                                                                                |
#' |                      | `  `  | ∙ YTH – Youth Authority School                                                                                                                                                                                                                                                                                                                                                                                            |
#' |                      | `  `  | ∙ SSS – State Special School                                                                                                                                                                                                                                                                                                                                                                                              |
#' |                      | `  `  | ∙ SPEC – Special Education School                                                                                                                                                                                                                                                                                                                                                                                         |
#' |                      | `  `  | ∙ TRAD – Traditional                                                                                                                                                                                                                                                                                                                                                                                                      |
#' |                      | `  `  | ∙ ROP – Regional Occupational Program                                                                                                                                                                                                                                                                                                                                                                                     |
#' |                      | `  `  | ∙ HOMHOS – Home and Hospital                                                                                                                                                                                                                                                                                                                                                                                              |
#' |                      | `  `  | ∙ SPECON – District Consortia Special Education School                                                                                                                                                                                                                                                                                                                                                                    |
#' | EdOpsName            | `  `  | The Educational Option Name is the long text description of  the type of education being offered. (See text values in EdOPsCode field description above)                                                                                                                                                                                                                                                                  |
#' | EILCode              | `  `  | The Educational Instruction Level Code is a short text description of the institution's type relative to the grade range served.                                                                                                                                                                                                                                                                                          |
#' |                      | `  `  | ∙ A – Adult                                                                                                                                                                                                                                                                                                                                                                                                               |
#' |                      | `  `  | ∙ ELEM – Elementary                                                                                                                                                                                                                                                                                                                                                                                                       |
#' |                      | `  `  | ∙ ELEMHIGH – Elementary-High Combination                                                                                                                                                                                                                                                                                                                                                                                  |
#' |                      | `  `  | ∙ HS – High School                                                                                                                                                                                                                                                                                                                                                                                                        |
#' |                      | `  `  | ∙ INTMIDJR – Intermediate/Middle/Junior High                                                                                                                                                                                                                                                                                                                                                                              |
#' |                      | `  `  | ∙ PS – Preschool                                                                                                                                                                                                                                                                                                                                                                                                          |
#' |                      | `  `  | ∙ UG – Ungraded                                                                                                                                                                                                                                                                                                                                                                                                           |
#' | EILName              | `  `  | The Educational Instruction Level Name is the long text description of the institution’s type relative to the grade range  served. (See text values in EILCode field description  above)                                                                                                                                                                                                                                  |
#' | GSoffered            | `  `  | The grade span offered is the lowest grade and the highest grade  offered or supported by the school, district, or administrative   authority. This field might differ from the grade span served as  reported in  the most recent certified California Longitudinal Pupil  Achievement (CALPADS)  Fall 1 data collection. For example XYZ School might display the following data: GSoffered = P–Adult, GSserved = K–12  |
#' | GSserved             | `  `  | This field represents the grade span served. It is the  lowest grade and the highest grade of student enrollment as reported in the   most recent certified CALPADS Fall 1 data collection. Only K–12  enrollment is  reported through CALPADS. This field may differ from the  grade span offered.                                                                                                                       |
#' |                      | `  `  | ∙ Note: Special programs at independent study, alternative education,  and special  education schools will often exceed the typical grade span  for schools of that  type (i.e., a high school might serve grades three  through twelve).                                                                                                                                                                                 |
#' | Virtual              | `  `  | This field identifies the type of virtual instruction offered by  the school. Virtual instruction is instruction in which students and  teachers are separated by time and/or location, and interaction occurs  via computers and/or telecommunications technologies. The field is coded as follows:                                                                                                                      |
#' |                      | `  `  | ∙ F = Exclusively Virtual – The school has no physical building where students meet with each other or with teachers, all instruction is virtual.                                                                                                                                                                                                                                                                         |
#' |                      | `  `  | ∙ V = Primarily Virtual – The school focuses on a systematic program of virtual instruction but includes some physical meetings among students or with teachers.                                                                                                                                                                                                                                                          |
#' |                      | `  `  | ∙ C = Primarily Classroom – The school offers virtual courses but virtual instruction is not the primary means of instruction.                                                                                                                                                                                                                                                                                            |
#' |                      | `  `  | ∙ N = Not Virtual – The school does not offer any virtual instruction.                                                                                                                                                                                                                                                                                                                                                    |
#' |                      | `  `  | ∙ P = Partial Virtual – The school offers some, but not all, instruction through virtual instruction. Note: This value was retired and replaced with the Primarily Virtual and Primarily Classroom values beginning with the 2016–17 school year.                                                                                                                                                                         |
#' | Magnet               | `  `  | This field identifies whether a school is a magnet school  and/or provides a magnet program. Additional information on magnet  schools may be obtained from the CDE Magnets web page. The field is coded as follows:                                                                                                                                                                                                      |
#' |                      | `  `  | ∙ Y = Magnet - The school is a magnet school and/or offers a magnet program.                                                                                                                                                                                                                                                                                                                                              |
#' |                      | `  `  | ∙ N = Not Magnet - The school is not a magnet school and/or does not offer a magnet program.                                                                                                                                                                                                                                                                                                                              |
#' |                      | `  `  | ∙ Note: Preschools and adult education centers do not contain a magnet school indicator.                                                                                                                                                                                                                                                                                                                                  |
#' | YearRoundYN          | `  `  | This field indicates if the school is operating on a year round  calendar. More information about year-round education can be found by  visiting the CDE Year-Round Education Program Guide web page.                                                                                                                                                                                                                     |
#' | FederalDFCDistrictID | `  `  | This field represents the 7-digit National Center for Educational Statistics (NCES) school district identification number for direct funded  charter schools. Beginning in February 2019, direct funded charter schools were  issued their own federal district ID and should nolonger use the federal  district ID associated with their authorizing agency.                                                             |
#' | Latitude             | `  `  | The angular distance (expressed in degrees) between the location  of the school,  district, or administrative authority and the equator  measured north to south.                                                                                                                                                                                                                                                         |
#' | Longitude            | `  `  | The angular distance (expressed in degrees) between the location  of the school,  district, or administrative authority and the prime  meridian (Greenwich,  England) measured from west to east.                                                                                                                                                                                                                         |
#' | AdmFName             | `  `  | The superintendent’s or principal’s first name. Only active and  pending districts  and schools will display administrator information,  if applicable.                                                                                                                                                                                                                                                                   |
#' | AdmLName             | `  `  | The superintendent’s or principal’s last name. Only active and  pending districts  and schools will display administrator information,  if applicable.                                                                                                                                                                                                                                                                    |
#' | AdmEmail             | `  `  | The superintendent’s or principal’s e-mail address. Only active  and pending  districts and schools will display administrator  information, if applicable.                                                                                                                                                                                                                                                               |
#' | LastUpDate           | `  `  | The date the record was last updated.                                                                                                                                                                                                                                                                                                                                                                                     |
#'
#' Further questions regarding this data can be sent by e-mail to
#' the Data Reporting Office at [dro@cde.ca.gov](dro@cde.ca.gov).
#'
#' @source
#' California Department of Education Data Reporting Office
#'
#' This data was downloaded Mon Jan 23 11:37:26 2023 and gathered from:
#' [https://www.cde.ca.gov/ds/si/ds/pubschls.asp](https://www.cde.ca.gov/ds/si/ds/pubschls.asp).
#'
#' @seealso \link{ca_dropouts},\link{ca_income_tax}
#'
"ca_schools"


#' Personal Income Tax Statistics By Zip Code
#'
#' @description
#' This dataset contains data from California resident tax returns filed with
#' California adjusted gross income and self-assessed tax listed by zip code.
#' This dataset contains data for taxable years 1992 to the most recent tax
#' year available.
#'
#' @details
#' | **Field Name**      |      | **Description**                                                          |
#' |---------------------|------|:-------------------------------------------------------------------------|
#' | Taxable Year        | `  ` | Tax year in which return was filed.                                      |
#' | Zip Code            | `  ` | Five-digit Zip Code associated with the tax return.                      |
#' | State               | `  ` | State, abbreviated, in which the return was filed.                       |
#' | City                | `  ` | City name in which the return was filed.                                 |
#' | County              | `  ` | County name in which the return was filed.                               |
#' | Returns             | `  ` | The number of returns filed for the designated taxable year and zip code.|
#' | CA AGI              | `  ` | California adjusted gross income.                                        |
#' | Total Tax Liability | `  ` | Amount of taxes owed.                                                    |
#'
#' Further questions regarding this data can be sent by e-mail to
#' FTB Open Data at [no-reply@data.ftb.ca.gov](no-reply@data.ftb.ca.gov).
#'
#' @source
#' California Franchise Tax Board
#'
#' This data was downloaded 2023/07/27 at 13:15:00 EST and gathered from:
#' [https://data.ca.gov/dataset/personal-income-tax-statistics-by-zip-code](https://data.ca.gov/dataset/personal-income-tax-statistics-by-zip-code).
#'
#' @seealso \link{ca_schools},\link{ca_dropouts}
#'
"ca_income_tax"

